-- MySQL Script generated by MySQL Workbench
-- qui 11 set 2025 14:36:35
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pizzaria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pizzaria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pizzaria` ;
USE `pizzaria` ;

-- -----------------------------------------------------
-- Table `pizzaria`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `data_ani` DATE NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `foto` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`idcliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzaria`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(80) NOT NULL,
  `email` VARCHAR(90) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `tipo` ENUM('cliente', 'adm') NULL DEFAULT 'cliente',
  PRIMARY KEY (`idusuario`),
  UNIQUE INDEX `uq_usuario` (`usuario` ASC) VISIBLE,
  UNIQUE INDEX `uq_email` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzaria`.`endentrega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`endentrega` (
  `idendentrega` INT NOT NULL AUTO_INCREMENT,
  `rua` VARCHAR(150) NOT NULL,
  `numero` VARCHAR(20) NOT NULL,
  `complemento` VARCHAR(50) NULL DEFAULT NULL,
  `bairro` VARCHAR(100) NOT NULL,
  `cliente` INT NOT NULL,
  PRIMARY KEY (`idendentrega`),
  INDEX `fk_endentrega_cliente_idx` (`cliente` ASC) VISIBLE,
  CONSTRAINT `fk_endentrega_cliente`
    FOREIGN KEY (`cliente`)
    REFERENCES `pizzaria`.`cliente` (`idcliente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzaria`.`pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`pagamento` (
  `idpagamento` INT NOT NULL AUTO_INCREMENT,
  `metodo_pagamento` ENUM('pix', 'cartao_debito', 'cartao_credito', 'dinheiro') NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `status_pagamento` ENUM('pendente', 'concluido', 'falhado', 'cancelado') NOT NULL,
  `data_pagamento` DATETIME NOT NULL,
  PRIMARY KEY (`idpagamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzaria`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`pedido` (
  `idpedido` INT NOT NULL AUTO_INCREMENT,
  `cliente` INT NOT NULL,
  `idfeedback` INT NULL DEFAULT NULL,
  `idpagamento` INT NOT NULL,
  `valortotal` DECIMAL(10,2) NOT NULL,
  `endentrega` INT NOT NULL,
  `status` ENUM('pendente', 'preparando', 'a_entrega', 'entregue', 'cancelado') NULL DEFAULT 'pendente',
  `estimativa_minutos` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idpedido`),
  INDEX `fk_pedido_cliente_idx` (`cliente` ASC) VISIBLE,
  INDEX `fk_pedido_pagamento_idx` (`idpagamento` ASC) VISIBLE,
  INDEX `fk_pedido_endentrega_idx` (`endentrega` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_cliente`
    FOREIGN KEY (`cliente`)
    REFERENCES `pizzaria`.`cliente` (`idcliente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pedido_pagamento`
    FOREIGN KEY (`idpagamento`)
    REFERENCES `pizzaria`.`pagamento` (`idpagamento`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pedido_endentrega`
    FOREIGN KEY (`endentrega`)
    REFERENCES `pizzaria`.`endentrega` (`idendentrega`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzaria`.`feedback`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`feedback` (
  `idfeedback` INT NOT NULL AUTO_INCREMENT,
  `assunto` VARCHAR(100) NOT NULL,
  `comentario` VARCHAR(2000) NOT NULL,
  `nota` TINYINT NULL DEFAULT NULL,
  `pedido_id` INT NULL DEFAULT NULL,
  `cliente_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idfeedback`),
  INDEX `fk_feedback_pedido_idx` (`pedido_id` ASC) VISIBLE,
  INDEX `fk_feedback_cliente_idx` (`cliente_id` ASC) VISIBLE,
  CONSTRAINT `fk_feedback_pedido`
    FOREIGN KEY (`pedido_id`)
    REFERENCES `pizzaria`.`pedido` (`idpedido`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_feedback_cliente`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `pizzaria`.`cliente` (`idcliente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzaria`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`produto` (
  `idproduto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `tipo` ENUM('pizza', 'bebida', 'promocao') NOT NULL,
  `tamanho` VARCHAR(45) NULL DEFAULT NULL,
  `preco` DECIMAL(10,2) NOT NULL,
  `foto` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`idproduto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzaria`.`pedido_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`pedido_produto` (
  `idpedido` INT NOT NULL,
  `idproduto` INT NOT NULL,
  `quantidade` INT NOT NULL,
  PRIMARY KEY (`idpedido`, `idproduto`),
  INDEX `fk_pedido_produto_produto_idx` (`idproduto` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_produto_pedido`
    FOREIGN KEY (`idpedido`)
    REFERENCES `pizzaria`.`pedido` (`idpedido`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pedido_produto_produto`
    FOREIGN KEY (`idproduto`)
    REFERENCES `pizzaria`.`produto` (`idproduto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzaria`.`delivery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`delivery` (
  `iddelivery` INT NOT NULL AUTO_INCREMENT,
  `pedido_id` INT NOT NULL,
  `status` ENUM('atribuido', 'a_caminho', 'entregue', 'falha') NULL DEFAULT 'atribuido',
  `iniciado_em` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `entregue_em` DATETIME NULL DEFAULT NULL,
  UNIQUE INDEX (`pedido_id` ASC) VISIBLE,
  PRIMARY KEY (`iddelivery`),
  CONSTRAINT `fk_delivery_pedido`
    FOREIGN KEY (`pedido_id`)
    REFERENCES `pizzaria`.`pedido` (`idpedido`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


INSERT INTO usuario (usuario, email, senha, tipo) 
VALUES ('Administrador', 'admin@pizzaria.com', '$2y$10$iEmilq/3TWnh.vKZHJ9jG.NdwVSI9CE5mi0EaeFuSnfiPBcd0JPbS', 'adm');