-- MySQL Script generated by MySQL Workbench
-- qua 29 out 2025 13:54:52
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pizzaria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pizzaria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pizzaria` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `pizzaria` ;

-- -----------------------------------------------------
-- Table `pizzaria`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(80) NOT NULL,
  `email` VARCHAR(90) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `tipo` ENUM('cliente', 'adm') NOT NULL DEFAULT 'cliente',
  PRIMARY KEY (`idusuario`),
  UNIQUE INDEX `uq_usuario` (`usuario` ASC) VISIBLE,
  UNIQUE INDEX `uq_email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `pizzaria`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `data_ani` DATE NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `foto` VARCHAR(255) NULL DEFAULT NULL,
  `idusuario` INT NOT NULL,
  PRIMARY KEY (`idcliente`),
  INDEX `fk_cliente_usuario_idx` (`idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_usuario`
    FOREIGN KEY (`idusuario`)
    REFERENCES `pizzaria`.`usuario` (`idusuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `pizzaria`.`endentrega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`endentrega` (
  `idendentrega` INT NOT NULL AUTO_INCREMENT,
  `rua` VARCHAR(150) NOT NULL,
  `numero` VARCHAR(20) NOT NULL,
  `complemento` VARCHAR(50) NULL DEFAULT NULL,
  `bairro` VARCHAR(100) NOT NULL,
  `idcliente` INT NULL DEFAULT NULL,
  `tipo` ENUM('cliente', 'ponto_fixo') NOT NULL DEFAULT 'cliente',
  PRIMARY KEY (`idendentrega`),
  INDEX `fk_endentrega_cliente_idx` (`idcliente` ASC) VISIBLE,
  CONSTRAINT `fk_endentrega_cliente`
    FOREIGN KEY (`idcliente`)
    REFERENCES `pizzaria`.`cliente` (`idcliente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `pizzaria`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`pedido` (
  `idpedido` INT NOT NULL AUTO_INCREMENT,
  `idcliente` INT NOT NULL,
  `valortotal` DECIMAL(10,2) NOT NULL,
  `identrega` INT NOT NULL,
  `data_pedido` DATETIME NOT NULL,
  `status` ENUM('pendente', 'preparando', 'pronto', 'cancelado') NOT NULL DEFAULT 'pendente',
  PRIMARY KEY (`idpedido`),
  INDEX `fk_pedido_cliente_idx` (`idcliente` ASC) VISIBLE,
  INDEX `fk_pedido_endentrega_idx` (`identrega` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_cliente`
    FOREIGN KEY (`idcliente`)
    REFERENCES `pizzaria`.`cliente` (`idcliente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pedido_endentrega`
    FOREIGN KEY (`identrega`)
    REFERENCES `pizzaria`.`endentrega` (`idendentrega`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `pizzaria`.`pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`pagamento` (
  `idpagamento` INT NOT NULL AUTO_INCREMENT,
  `idcliente` INT NOT NULL,
  `metodo_pagamento` ENUM('pix', 'cartao_debito', 'cartao_credito', 'dinheiro') NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `status_pagamento` ENUM('pendente', 'concluido', 'falhado', 'cancelado') NOT NULL,
  `data_pagamento` DATETIME NOT NULL,
  `idpedido` INT NOT NULL,
  PRIMARY KEY (`idpagamento`),
  INDEX `fk_pagamento_cliente1_idx` (`idcliente` ASC) VISIBLE,
  INDEX `fk_pagamento_pedido1_idx` (`idpedido` ASC) VISIBLE,
  CONSTRAINT `fk_pagamento_cliente1`
    FOREIGN KEY (`idcliente`)
    REFERENCES `pizzaria`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pagamento_pedido1`
    FOREIGN KEY (`idpedido`)
    REFERENCES `pizzaria`.`pedido` (`idpedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `pizzaria`.`feedback`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`feedback` (
  `idfeedback` INT NOT NULL AUTO_INCREMENT,
  `assunto` VARCHAR(100) NOT NULL,
  `comentario` VARCHAR(2000) NOT NULL,
  `nota` TINYINT NULL DEFAULT NULL,
  `cliente_id` INT NULL DEFAULT NULL,
  `idpedido` INT NOT NULL,
  PRIMARY KEY (`idfeedback`),
  INDEX `fk_feedback_cliente_idx` (`cliente_id` ASC) VISIBLE,
  INDEX `fk_feedback_pedido1_idx` (`idpedido` ASC) VISIBLE,
  CONSTRAINT `fk_feedback_cliente`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `pizzaria`.`cliente` (`idcliente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_feedback_pedido1`
    FOREIGN KEY (`idpedido`)
    REFERENCES `pizzaria`.`pedido` (`idpedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `pizzaria`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`produto` (
  `idproduto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `tipo` ENUM('pizza', 'bebida', 'promocao') NOT NULL,
  `tamanho` VARCHAR(45) NULL DEFAULT NULL,
  `preco` DECIMAL(10,2) NOT NULL,
  `foto` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`idproduto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `pizzaria`.`pedido_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`pedido_produto` (
  `idpedido` INT NOT NULL,
  `idproduto` INT NOT NULL,
  `quantidade` INT NOT NULL,
  `preco_unit` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`idpedido`, `idproduto`),
  INDEX `fk_pedido_produto_produto_idx` (`idproduto` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_produto_pedido`
    FOREIGN KEY (`idpedido`)
    REFERENCES `pizzaria`.`pedido` (`idpedido`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pedido_produto_produto`
    FOREIGN KEY (`idproduto`)
    REFERENCES `pizzaria`.`produto` (`idproduto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `pizzaria`.`delivery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`delivery` (
  `iddelivery` INT NOT NULL AUTO_INCREMENT,
  `pedido_id` INT NOT NULL,
  `status` ENUM('atribuido', 'a_caminho', 'entregue', 'falha') NOT NULL DEFAULT 'atribuido',
  `iniciado_em` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `entregue_em` DATETIME NULL DEFAULT NULL,
  UNIQUE INDEX `uq_delivery_pedido` (`pedido_id` ASC) VISIBLE,
  PRIMARY KEY (`iddelivery`),
  CONSTRAINT `fk_delivery_pedido`
    FOREIGN KEY (`pedido_id`)
    REFERENCES `pizzaria`.`pedido` (`idpedido`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


CREATE TABLE IF NOT EXISTS `pizzaria`.`carrinho` (
  `idcarrinho` INT NOT NULL AUTO_INCREMENT,
  `idproduto` INT NOT NULL,
  `idcliente` INT NOT NULL,
  `quantidade` INT NOT NULL DEFAULT 1,
  `data_adicionado` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idcarrinho`),
  INDEX `fk_carrinho_produto_idx` (`idproduto` ASC),
  INDEX `fk_carrinho_cliente_idx` (`idcliente` ASC),
  CONSTRAINT `fk_carrinho_produto`
    FOREIGN KEY (`idproduto`)
    REFERENCES `pizzaria`.`produto` (`idproduto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_carrinho_cliente`
    FOREIGN KEY (`idcliente`)
    REFERENCES `pizzaria`.`cliente` (`idcliente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


USE `pizzaria`;

DELIMITER $$
USE `pizzaria`$$
CREATE TRIGGER trg_pedido_cancelado
AFTER UPDATE ON pedido
FOR EACH ROW
BEGIN
    IF NEW.status = 'cancelado' AND OLD.status <> 'cancelado' THEN
        UPDATE delivery
        SET status = 'falha'
        WHERE pedido_id = NEW.idpedido;
    END IF;
END$$

USE `pizzaria`$$
CREATE TRIGGER trg_delivery_entregue
AFTER UPDATE ON delivery
FOR EACH ROW
BEGIN
    IF NEW.status = 'entregue' AND OLD.status <> 'entregue' THEN
        UPDATE pedido
        SET status = 'pronto'
        WHERE idpedido = NEW.pedido_id;
    END IF;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO `usuario` (`usuario`, `email`, `senha`, `tipo`)
VALUES ('Administrador', 'admin@pizzaria.com', '$2y$10$iEmilq/3TWnh.vKZHJ9jG.NdwVSI9CE5mi0EaeFuSnfiPBcd0JPbS', 'adm');

INSERT INTO endentrega (rua, numero, complemento, bairro, idcliente, tipo)
VALUES ('Av. Central', '1000', 'Retirada no Local', 'Centro', NULL, 'ponto_fixo');